import type { GameMeta } from "./types";

export const GAMES: GameMeta[] = [
  {
    id: "tic-tac-toe",
    title: "Tic Tac Toe",
    subtitle: "Classic 3×3 duel",
    emoji: "⭕",
    category: "classic",
    gradient: "from-violet-500 to-fuchsia-500",
    multiplayer: "both",
    tags: ["2 players", "quick"],
    popular: true,
  },
  {
    id: "chess",
    title: "Chess",
    subtitle: "Master the board",
    emoji: "♟️",
    category: "board",
    gradient: "from-amber-500 to-orange-600",
    multiplayer: "both",
    tags: ["strategy", "2 players"],
    popular: true,
  },
  {
    id: "ludo",
    title: "Ludo",
    subtitle: "Race your tokens home",
    emoji: "🎲",
    category: "board",
    gradient: "from-emerald-500 to-teal-500",
    multiplayer: "both",
    tags: ["family", "dice"],
    popular: true,
  },
  {
    id: "snakes-ladders",
    title: "Snakes & Ladders",
    subtitle: "Climb up, slide down",
    emoji: "🪜",
    category: "board",
    gradient: "from-lime-500 to-green-600",
    multiplayer: "both",
    tags: ["luck", "family"],
  },
  {
    id: "truth-or-dare",
    title: "Truth or Dare",
    subtitle: "Party sparks & laughs",
    emoji: "🔥",
    category: "party",
    gradient: "from-rose-500 to-pink-600",
    multiplayer: "both",
    tags: ["party", "friends"],
    popular: true,
  },
  {
    id: "snake",
    title: "Snake",
    subtitle: "Grow without crashing",
    emoji: "🐍",
    category: "arcade",
    gradient: "from-green-400 to-emerald-600",
    multiplayer: "local",
    tags: ["arcade", "high score"],
    popular: true,
  },
  {
    id: "pac-man",
    title: "Pac Maze",
    subtitle: "Eat dots, dodge ghosts",
    emoji: "👻",
    category: "arcade",
    gradient: "from-yellow-400 to-amber-500",
    multiplayer: "local",
    tags: ["retro", "maze"],
    popular: true,
  },
  {
    id: "runner",
    title: "Sky Runner",
    subtitle: "Endless parkour rush",
    emoji: "🏃",
    category: "arcade",
    gradient: "from-cyan-400 to-blue-600",
    multiplayer: "local",
    tags: ["endless", "reflex"],
    popular: true,
  },
  {
    id: "carrom",
    title: "Carrom Strike",
    subtitle: "Flick coins into pockets",
    emoji: "🎯",
    category: "board",
    gradient: "from-amber-600 to-yellow-500",
    multiplayer: "both",
    tags: ["skill", "2 players"],
  },
  {
    id: "connect-four",
    title: "Connect Four",
    subtitle: "Line up four in a row",
    emoji: "🔴",
    category: "classic",
    gradient: "from-red-500 to-rose-600",
    multiplayer: "both",
    tags: ["strategy", "2 players"],
  },
  {
    id: "memory",
    title: "Memory Match",
    subtitle: "Flip pairs, beat the clock",
    emoji: "🧠",
    category: "puzzle",
    gradient: "from-indigo-500 to-purple-600",
    multiplayer: "both",
    tags: ["brain", "pairs"],
  },
  {
    id: "game-2048",
    title: "2048",
    subtitle: "Merge tiles to win",
    emoji: "🔢",
    category: "puzzle",
    gradient: "from-orange-400 to-amber-500",
    multiplayer: "local",
    tags: ["puzzle", "merge"],
  },
  {
    id: "rock-paper-scissors",
    title: "Rock Paper Scissors",
    subtitle: "Best of three showdown",
    emoji: "✊",
    category: "party",
    gradient: "from-slate-500 to-zinc-600",
    multiplayer: "both",
    tags: ["quick", "2 players"],
  },
  {
    id: "brick-breaker",
    title: "Brick Breaker",
    subtitle: "Smash every brick",
    emoji: "🧱",
    category: "arcade",
    gradient: "from-sky-500 to-indigo-600",
    multiplayer: "local",
    tags: ["arcade", "paddle"],
  },
  {
    id: "checkers",
    title: "Checkers",
    subtitle: "Jump and crown kings",
    emoji: "⚫",
    category: "board",
    gradient: "from-stone-600 to-neutral-800",
    multiplayer: "both",
    tags: ["strategy", "2 players"],
  },
];

export function getGame(id: string): GameMeta | undefined {
  return GAMES.find((g) => g.id === id);
}
